NewPlayer = sprites.create(img("""
        ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff......ccc.
            .ffefbf44fbfeff....cddc.
            .ffefbf44fbfeff...cddc..
            .fee4dddddd4eef.ccddc...
            fdfeeddddd4eeffecddc....
            fbffee4444ee4fddccc.....
            fbf4f222222f1edde.......
            fcf.f222222f44ee........
            .ff.f445544f............
            ....ffffffff............
            .....ff..ff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
    """),
    SpriteKind.player)
game.show_long_text("""Think of one of these animals: 
        Dog, Cat, Eagle, Penguin, Shark, Dolphin, Snake, Frog
    """,
    DialogLayout.CENTER)
answer = game.ask("Does it live in water?")
if answer == True:
    answer = game.ask("Is it a mammal?")
    if answer == True:
        NewPlayer.say_text("Its a Dolphin!")
    else:
        NewPlayer.say_text("Its a Shark!")
else:
    answer = game.ask("Does it have feathers?")
    if answer == True:
        answer = game.ask("Can it fly?")
        if answer == True:
            NewPlayer.say_text("Its an Eagle!")
        else:
            NewPlayer.say_text("Its a Penguin!")
    else:
        answer = game.ask("Is it a reptile?")
        if answer == True:
            NewPlayer.say_text("Its a Snake!")
        else:
            answer = game.ask("Is it a mammal?")
            if answer == True:
                answer = game.ask("Does it bark?")
                if answer == True:
                    NewPlayer.say_text("Its")
                else:
                    NewPlayer.say_text("Its a Cat!")
            else:
                NewPlayer.say_text("It's a Frog!")