let NewPlayer = sprites.create(img`
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff......ccc.
    .ffefbf44fbfeff....cddc.
    .ffefbf44fbfeff...cddc..
    .fee4dddddd4eef.ccddc...
    fdfeeddddd4eeffecddc....
    fbffee4444ee4fddccc.....
    fbf4f222222f1edde.......
    fcf.f222222f44ee........
    .ff.f445544f............
    ....ffffffff............
    .....ff..ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
game.showLongText(`Think of one of these animals: 
        Dog, Cat, Eagle, Penguin, Shark, Dolphin, Snake, Frog
    `, DialogLayout.Center)
let answer = game.ask("Does it live in water?")
if (answer == true) {
    answer = game.ask("Is it a mammal?")
    if (answer == true) {
        NewPlayer.sayText("Its a Dolphin!")
    } else {
        NewPlayer.sayText("Its a Shark!")
    }
} else {
    answer = game.ask("Does it have feathers?")
    if (answer == true) {
        answer = game.ask("Can it fly?")
        if (answer == true) {
            NewPlayer.sayText("Its an Eagle!")
        } else {
            NewPlayer.sayText("Its a Penguin!")
        }
    } else {
        answer = game.ask("Is it a reptile?")
        if (answer == true) {
            NewPlayer.sayText("Its a Snake!")
        } else {
            answer = game.ask("Is it a mammal?")
            if (answer == true) {
                answer = game.ask("Does it bark?")
                if (answer == true) {
                    NewPlayer.sayText("Its")
                } else {
                    NewPlayer.sayText("Its a Cat!")
                }
            } else {
                NewPlayer.sayText("It's a Frog!")
            }
        }
    }
}
